### ISSUE TITLE
ld: library not found for -lwx_osx_cocoau_webview-3.0

### ISSUE THREAD

**Issue by MattPhantastic** [iMokhles/wxWidgets-Xcode-Template#1]
I installed the wxWidgets via Homebrew.

```
brew install wxwidgets
```

Opened the install.sh with Terminal.

I fired up Xcode 11.4 and created a project with the wxWidgets template that I just installed.

But for some reason, the pre-made project coming with the template won't build. It gives me the following error:

```
ld: library not found for -lwx_osx_cocoau_webview-3.0
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

And if I try running:

```
brew install -v --HEAD wxwidgets
```
It fails at this patching step:

```
==> Patching
patching file src/osx/carbon/dcclient.cpp
Hunk #1 FAILED at 189.
1 out of 1 hunk FAILED -- saving rejects to file src/osx/carbon/dcclient.cpp.rej
Error: Failure while executing; `patch -g 0 -f -p1` exited with 1. Here's the output:
1028
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC.
```

Any help will be much appreciated.

**Comment by dorald** [comment]
I got the same error !! Any chance to fix that ?

**Comment by iMokhles** [comment]
sorry for the delay thanks @dorald for commenting on this issue, it's fixed now you can re-clone the repo again.
